"""Regression test over the weighted scoring formula.

The other reviewer tests probe one behaviour each with a small hand-built case.
This one freezes a whole panel and the exact numbers it must produce, so a change
to the weights, the formula, the threshold or the ranking shows up as a failure
here and as a readable diff in the fixture.

The expected values in the fixture were computed from the formula in the
specification, not by running the synthesizer. A golden file generated by the
code under test only records what that code does today.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from nexis.agents.reviewers import ReviewSynthesizer
from nexis.config import PipelineConfig
from nexis.state import BusinessIdea, Review

FIXTURE = Path(__file__).resolve().parent / "evals" / "scoring_regression.json"

# Floating point addition is not associative, so the synthesizer may sum the
# terms in a different order than the fixture did.
TOLERANCE = 1e-9


@pytest.fixture(scope="module")
def fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


@pytest.fixture
def config(fixture: dict) -> PipelineConfig:
    return PipelineConfig(
        research_prompt="frozen panel, no research runs",
        reviewer_weights=fixture["weights"],
        score_threshold=fixture["score_threshold"],
        top_k=fixture["top_k"],
    )


@pytest.fixture
def ideas(fixture: dict) -> list[BusinessIdea]:
    return [
        BusinessIdea(
            id=idea_id,
            title=idea_id,
            problem_statement="frozen",
            target_market="frozen",
            revenue_model="frozen",
            confidence=0.7,
        )
        for idea_id in fixture["idea_ids"]
    ]


@pytest.fixture
def reviews(fixture: dict) -> list[Review]:
    return [Review.model_validate(row) for row in fixture["reviews"]]


@pytest.fixture
def result(reviews, config, ideas):
    return ReviewSynthesizer().synthesize(reviews=reviews, config=config, ideas=ideas)


class TestFixture:
    def test_the_frozen_panel_is_whole(self, fixture, reviews, ideas):
        """A truncated fixture would weaken every test below without failing one."""
        assert len(ideas) == 6
        assert len(reviews) == 32
        assert set(fixture["expected_scores"]) == set(fixture["idea_ids"])

    def test_the_weights_are_the_shipped_defaults(self, fixture):
        """The frozen numbers only mean something against the real weights."""
        shipped = PipelineConfig(research_prompt="x").reviewer_weights
        assert fixture["weights"] == shipped


class TestScoringRegression:
    def test_every_score_matches_the_frozen_value(self, result, fixture):
        scores, _ = result
        assert set(scores) == set(fixture["expected_scores"])
        for idea_id, expected in fixture["expected_scores"].items():
            assert scores[idea_id] == pytest.approx(expected, abs=TOLERANCE), idea_id

    def test_the_ranking_is_exact(self, result, fixture):
        _, top_ideas = result
        assert top_ideas == fixture["expected_top_ideas"]

    def test_ideas_are_ordered_by_score_descending(self, result):
        scores, top_ideas = result
        ordered = [scores[idea_id] for idea_id in top_ideas]
        assert ordered == sorted(ordered, reverse=True)

    def test_a_partial_panel_is_not_scaled_up(self, result, config):
        """Two reviewers out of six leave the score low; the formula does not renormalise."""
        scores, top_ideas = result
        assert scores["idea-delta"] == pytest.approx(0.292, abs=TOLERANCE)
        assert scores["idea-delta"] < config.score_threshold
        assert "idea-delta" not in top_ideas

    def test_a_panel_of_failed_reviews_scores_zero(self, result):
        """The failed rows carry high scores, and none of them may count."""
        scores, top_ideas = result
        assert scores["idea-epsilon"] == 0.0
        assert "idea-epsilon" not in top_ideas

    def test_the_threshold_drops_what_is_below_it(self, result, config):
        scores, top_ideas = result
        for idea_id, score in scores.items():
            if score < config.score_threshold:
                assert idea_id not in top_ideas

    def test_the_top_k_boundary_holds(self, result, config):
        _, top_ideas = result
        assert len(top_ideas) == config.top_k

    def test_close_scores_keep_their_order(self, result):
        """Alpha and zeta sit 0.01 apart, which is the case a weight change moves first."""
        scores, top_ideas = result
        assert top_ideas[0] == "idea-alpha"
        assert top_ideas[1] == "idea-zeta"
        assert scores["idea-alpha"] - scores["idea-zeta"] == pytest.approx(
            0.01, abs=1e-9
        )
